### ISSUE TITLE
duration_limit problem

### ISSUE THREAD

**Issue by MarcoMencucci** [vidalt/HGS-CVRP#47]
Is it possible that setting duration_limit when we have a large quantity of data brings the algorithm into a soft lock state where it fails to build the initial population ?

**Comment by vidalt** [comment]
It is possible that setting tight duration limits renders the problem infeasible. Since the algorithm is configured only to return feasible solutions, it would attempt to solve the problem but not return any feasible solution in that case. The population's initial creation should terminate in all cases, albeit with no feasible solution.
